export const SEED_LABS = [
  {
    id: "phd-nlp-01",
    name: "Dr. Nguyễn Văn An",
    labName: "Phòng Thí nghiệm Xử lý Ngôn ngữ Tự nhiên & LLMs",
    institution: "ĐHQG Hà Nội (VNU-HN)",
    domainKey: "natural_language_processing",
    domainCategory: "artificial_intelligence",
    domainLabelVi: "NLP",
    domainLabelEn: "NLP",
    trlMin: 3,
    trlMax: 8,
    typicalMonths: 24,
    papersCount: 14,
    sparkline: "M0,20 Q20,15 40,8 T80,4 T90,2",
  },
  {
    id: "phd-cv-02",
    name: "Dr. Trần Thị Mai",
    labName: "Viện Thị giác Máy tính & Robot Tự hành",
    institution: "ĐH Bách Khoa TP.HCM (HCMUT)",
    domainKey: "computer_vision",
    domainCategory: "artificial_intelligence",
    domainLabelVi: "Robot",
    domainLabelEn: "Robot",
    trlMin: 4,
    trlMax: 8,
    typicalMonths: 18,
    papersCount: 9,
    sparkline: "M0,22 Q25,18 45,10 T75,8 T90,3",
  },
  {
    id: "phd-mfg-04",
    name: "Dr. Phạm Đức Duy",
    labName: "Trung tâm Nghiên cứu Cơ điện tử & Tự động hóa",
    institution: "ĐH Sư phạm Kỹ thuật TP.HCM",
    domainKey: "manufacturing",
    domainCategory: "manufacturing",
    domainLabelVi: "Tự động hóa",
    domainLabelEn: "Automation",
    trlMin: 4,
    trlMax: 8,
    typicalMonths: 24,
    papersCount: 11,
    sparkline: "M0,24 Q30,19 50,14 T80,6 T90,5",
  },
  {
    id: "phd-bio-03",
    name: "Dr. Lê Thị Cẩm",
    labName: "Phòng Thí nghiệm Sinh học Phân tử",
    institution: "Đại học Y Hà Nội (HMU)",
    domainKey: "biomedical",
    domainCategory: "biomedical",
    domainLabelVi: "Y sinh",
    domainLabelEn: "Biomedical",
    trlMin: 2,
    trlMax: 6,
    typicalMonths: 36,
    papersCount: 21,
    sparkline: "M0,26 Q25,22 45,18 T70,12 T90,8",
  },
];
